[bumpver]
current_version = "v2025.10.2"
version_pattern = "vYYYY.MM.INC0"
commit_message = "chore: [skip build] bump version {old_version_pep440} -> {new_version_pep440}"
tag_message = "release {new_version_pep440}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"packages/react-google-recaptcha/package.json" = [
    '"version": "{pep440_version}"',
]
