packages:
  - examples
  - packages/**

# 重複排除
dedupePeers: true

catalog:
  react: &react_ver 19.2.7
  react-dom: *react_ver
  playwright: 1.63.0
  rolldown: 1.2.8
  rolldown-plugin-dts: 0.28.5
  turbo: 2.10.12
  typescript: 7.0.2
  vite: 8.2.2
  vitest: &vitest_ver 4.1.11
  vitest-browser-react: 2.3.0
  '@biomejs/biome': 2.5.12
  '@fast-check/vitest': 0.4.1
  '@types/node': 26.5.1
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  '@vitejs/plugin-react': 6.1.1
  '@vitest/coverage-v8': *vitest_ver
  '@vitest/browser-playwright': *vitest_ver
  '@vitest/expect': *vitest_ver
  '@vitest/mocker': *vitest_ver
  '@vitest/spy': *vitest_ver

overrides:
  # CVE-2026-67213
  nanoid: ^3.3.17
  rolldown: 'catalog:'
  '@vitest/expect': 'catalog:'
  '@vitest/mocker': 'catalog:'
  '@vitest/spy': 'catalog:'

# リリースから一定時間経過していないか、信頼性低下したパッケージはインストールしない
minimumReleaseAge: 2880 # 2d
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade

# 特殊なソースからの依存関係をインストールしない
blockExoticSubdeps: true
