packages:
  - examples
  - packages/**

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - lefthook

overrides:
  '@vitest/expect': $vitest
  '@vitest/mocker': $vitest
  '@vitest/spy': $vitest
